//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CargoCalculator.DBContext
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PriceConfig
    {
        public int PriceConfigid { get; set; }
        public int PartnerId { get; set; }
        public int PriceTypeId { get; set; }

        [Display(Name = "Start Range")]
        public Nullable<decimal> StartRange { get; set; }
        [Display(Name = "End Range")]
        public Nullable<decimal> EndRange { get; set; }
        [Display(Name = "Price")]
        public Nullable<decimal> Price { get; set; }
        public Nullable<bool> IsActive { get; set; }
        [Display(Name = "ExtraVolumeThreshold")]
        public Nullable<decimal> ExtraVolumeThreshold { get; set; }
        [Display(Name = "ExtraVolumeThreshold")]
        public Nullable<decimal> ExtraPerValumePrice { get; set; }
        [Display(Name = "Extra Weight Threshold")]
        public Nullable<decimal> ExtraWeightThreshold { get; set; }
        [Display(Name = "Extra Weight Price(per/Kg)")]
        public Nullable<decimal> ExtraPerWeightPrice { get; set; }
    
        public virtual Partner tblMstPartner { get; set; }
        public virtual PriceType tblMstPriceType { get; set; }
    }
}
