//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CargoCalculator.DBContext
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Report
    {
        public int id { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Depth { get; set; }
        public Nullable<decimal> Weight { get; set; }
        [Display(Name = "Dimention Price")]
        public Nullable<decimal> DimentionPrice { get; set; }
        [Display(Name = "Weigh Price")]
        public Nullable<decimal> weightPrice { get; set; }
        [Display(Name = "Final Price")]
        public Nullable<decimal> FinalPrice { get; set; }
        [Display(Name = "Date")]
        public Nullable<System.DateTime> FetchDate { get; set; }
        public string UserId { get; set; }
        [Display(Name = "User Name")]
        public string UserName { get; set; }
        [Display(Name = "Partner Id")]
        public Nullable<int> PartnerId { get; set; }
        [Display(Name = "Partner Name")]
        public string PartnerName { get; set; }
        [Display(Name = "Extra Weight")]
        public Nullable<decimal> ExtraWeight { get; set; }
        [Display(Name = "Extra Weight Price")]
        public Nullable<decimal> TotalExtraWeightPrice { get; set; }
    }
}
