//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CargoCalculator.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int id { get; set; }
        public int PartnerIdForWeightPrice { get; set; }
        public int PartnerIdForAreaPrice { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Depth { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> PriceForWeight { get; set; }
        public Nullable<decimal> PriceForArea { get; set; }
        public Nullable<System.DateTime> FetchDate { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
    
        public virtual Partner tblMstPartner { get; set; }
        public virtual Partner tblMstPartner1 { get; set; }
    }
}
